# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

target 'Jmagine' do
  # Comment the next line if you're not using Swift and don't want to use dynamic frameworks
  use_frameworks!
pod 'SideMenu'
pod 'Alamofire', '4.8.1'
pod "SwiftyXMLParser", :git => 'https://github.com/yahoojapan/SwiftyXMLParser.git'
pod 'XMLParsing', :git => 'https://github.com/ShawnMoore/XMLParsing.git'
  # Pods for Jmagine

end
